MobiFlight/MobiFlight-FirmwareSource

_Boards/Atmel/Board_Mega/MFBoards.h, _Boards/Atmel/Board_ProMicro/MFBoards.h
Founds several places where there were mismatches in MFBoards.h from the source currently checked in to https://github.dev/MobiFlight/MobiFlight-Connector/blob/51613650fa8142f4a7338633dac631e2ec33fb2a/FirmwareSource/mobiflight/mobiflight.ino.
Updated the files so they replicate the currently shipping settings.
=> Clean up MFBoards.h files to match current values

src/mobiflight.cpp
Add a missing macro to convert the environment variable from command line build flags into an actual #define in code.
=> Fix the verison number during build time

platformio.ini
Fixes #82
Change the name of the platform in platformio.ini so the firmware has the correct name
=> ProMicro filename is wrong

.tours/how-firmware-versions-are-set.tour
Fixes #72
Add a Visual Studio CodeTour to explain all pieces that go into setting the firmware version at build time.
Tour overview:
Example of a step in the tour:
=> Add CodeTour explaining how versioning works

src/MF_Modules/MFEncoder.cpp
Fixes #97
To keep backwards compatibility for encoder type digitalRead must be negated
=> Encoder behaviour changed w/ new platformIO build

src/MF_Modules/MFShifter.cpp
(Replaces PR #79)
Fixes  #80:
The count of bytes shifted out was incorrect. It did not affect operation because the excess byte was on the tail end and was discarded, however it unnecessarily increased timing and might cause problems in the future.
=> Fix: corrected byte count in shift (NEW PR)

.vscode/extensions.json
Fixes #89
Adds the CodeTour extension to `.vscode/extensions.json`.
=> Add CodeTour to recommended VSCode extensions

src/MF_Modules/MFLCDDisplay.cpp, src/mobiflight.cpp
Fixes #85
Instead of copying the single line to a buffer, print directly from the char buffer containing the complete message via ->write().
Tested with a 20x4 LCD, but will work with any combination of columns and rows.
=> Support any combination of row/column counts for LCD displays

platformio.ini, src/MF_Modules/MFLCDDisplay.cpp
With pull request https://github.com/MobiFlight/LiquidCrystal_I2C/pull/1 the parameters are moved from the constructor to the init() function. Therefore this has to be changed also in the firmware.
=> Changes for modified LiquidCrystal_I2C lib

include/mobiflight.h, src/mobiflight.cpp
Read in time for buttons reduced from 11ms to 10ms as originally intended
Read in time for analog average reduced from 11ms to 10ms as originally intended
Fixes #113
=> Read time for buttons and analog in is wrong Fixes #113

include/MFServo.h, include/mobiflight.h, src/MF_Modules/MFServo.cpp, src/mobiflight.cpp
Fixes #107
Servo update code now defers processing for at least 5ms for each tick. This ensures the servo's internally tracked position isn't moved towards the goal at a non-regulated rate. As a result the servo movement appears smoother, especially in the case of config timer internal being set to higher values.
=> Enabled deferring of servo processing to smooth movement

src/MF_Modules/MFEncoder.cpp
Fixes #120
First step of an encoder after startup is always a fast step. This is due to missing initialization of _positionTimePrev and _positionTime. Therefore they have the same value and a high speed is calculated.
=> After start first step of enc is always fast step

src/mobiflight.cpp
Fixes #123
configBuffer was on every part of the upload written up to the end of the buffersize. Every byte after the config part came from "somewhere".
With this change only the received part of the config  gets copied.
=> Config Buffer gets filled with unnecessary bytes

src/mobiflight.cpp
Fixes #128
Move two strings to PROGMEM. On a ProMicro before this change:
```
RAM:   [========  ]  77.5% (used 1984 bytes from 2560 bytes)
Flash: [========= ]  91.6% (used 26254 bytes from 28672 bytes)
```
On a ProMicro after this change:
```
RAM:   [========  ]  76.6% (used 1962 bytes from 2560 bytes)
Flash: [========= ]  91.7% (used 26290 bytes from 28672 bytes)
```
Saves 22 bytes of RAM at the expense of 36 bytes of flash.
=> Use progmem for two fixed strings

README.md, get_version.py
Fixes #125
* Strip any leading "v" off the version
* Strip any leading or trailing dots off the version
=> Clean up version number before build

src/mobiflight.cpp
Fixes #130
* Add missing #if statements for the analog and servo variables.
* Re-order the two places where those variables are mentioned to be consistent.
=> Add missing #if for analog and servo

platformio.ini
Fixes #144
Created common `env` sections for the parts of the build definition that are common across all boards.
=> Move common platform.ini pieces to a shared environment block

include/MFSegments.h, src/MF_Modules/MFSegments.cpp
Implements part of #642: now setting Brightness = 0 completely switches the display off rather than setting minimum brightness.
Actual value sent to the IC is lower by 1 (actual range: 0-14), since value 15 is effectively indistinguishable from 14, but value 0 is a very faint brightness that might be desired in some cases.
Memory occupation has been very slightly reduced by using the value of "_moduleCount" to replace the "_initialized" flag
=> Issue #151 - Brightness=0 completely switches display off

src/MF_Modules/MFOutputShifter.cpp
Fixes #155
* Added `- 1` to array indexing when sending values out to the shift registers
* Remove commented out code that shouldn't be in the source
=> Fix off by one error in output shifter indexing

src/MF_Modules/MFLCDDisplay.cpp
Check if string to be printed is longer than available columns. If so an "overflow" of 'c' happens and a lot of spaces are printed to the LCD which seems to crash the Arduino. By checking this condition and not printing spaces this crash is avoided.
I thought some time to check this in the LiquidCrystal_I2C library, but that would mean a lot of modifications as the column is not tracked there. The test() function here is the only place where this could happen so it's easier to make the modifications here.
Fixes #158
=> avoid crash if string is longer then columns, Fixes #158

_Boards/Atmel/Board_Uno/MFBoards.h
Fixes #161
* Set max button count to 18
* Set max output count to 18
* Set max analog input count to 6
=> Increase device limits on the Uno

src/Config.cpp
Fixes #170
configLenght=0 and configActivated=false must not be encapsulated within MF_INPUT_SHIFTER_SUPPORTT==1
=> Config gets not "resetted" if InputShifter is deactivated

src/Config.cpp, src/MF_Modules/MFEEPROM.cpp, src/MF_Modules/MFEEPROM.h, src/config.h, src/mobiflight.cpp
Addresses #172:
`config` parameters collected in a single struct for better encapsulation and readability
Added EEPROM function aliases to avoid unnecessary parameter passing (and improve readability)
Some variable names changed for consistency
=> Improvement of pointer handling in EEPROM functions for config parsing

src/CommandMessenger.cpp, src/MF_LCDDisplay/LCDDisplay.cpp
Fixes #178 
Added unescape method to LCDDisplay when reading String Arg to allow for proper display of special characters.
=> Unescape special characters for LCD Display

src/Config.cpp
After changing and uploading a new config the devive buffer gets not cleared. Added the missing function solves this issue.
Fixes #181
=> Device Buffer get's not cleared if a config is uploaded

_Boards/Atmel/Board_ProMicro/MFBoards.h, _Boards/Atmel/Board_Uno/MFBoards.h
The max. number of encoders is increased to 9 for Uno and ProMicro. All available 18 Pins can be used for encoders.
Fixes #180
=> Increase number of encoders for Uno and ProMicro

platformio.ini
To avoid warning of deprecated function replace src_filter by build_src_filter
Fixes #184
=> platformio.ini uses deprecated `src_filter`

src/CommandMessenger.cpp, src/Config.cpp, src/MF_Analog/Analog.cpp, src/MF_Button/Button.cpp, src/MF_DigInMux/DigInMux.cpp, src/MF_Encoder/Encoder.cpp, src/MF_InputShifter/InputShifter.cpp, src/MF_LCDDisplay/LCDDisplay.cpp, src/MF_Output/Output.cpp, src/MF_OutputShifter/OutputShifter.cpp, src/MF_Segment/LedSegment.cpp, src/MF_Servo/Servos.cpp, src/MF_Stepper/Stepper.cpp, src/allocateMem.cpp, src/commandmessenger.h, src/mobiflight.cpp
Debug prints send via the commandmessenger are marked with kStatus. This is changed to KDebug to seperate them from status messages.
With changes in the UI the will appear if loglevel is debug.
Fixes #188
=> Add firmware debug printouts to log in the UI

src/MF_Modules/MFEEPROM.cpp, src/MF_Modules/MFEEPROM.h, src/mobiflight.cpp
1. Like @GioCC always proposed, read/write block and write byte returns true or false (not used for now)
2. private variable `eepromLength ` is cahnged to `_eepromLength ` like in other MF classes.
3. If last eeprom location was addressed at read/write block complete block was not written/read
4. `MFEEPROM `needs separate `init()` for C++ compliance. `MFEEPROM `and `EEPROM `are global classes, and "correct" order of constructors can not be ensured. This is more a relevant for additional hardware/frameworks, but it might also a topic for the  future.
I am also fine if @GioCC includes it in his PR #175 (some are already included).
Fixes #186
=> Optimization of MFEEPROM class

src/MF_Button/MFButton.cpp, src/MF_InputShifter/InputShifter.cpp, src/MF_InputShifter/MFInputShifter.cpp, src/MF_InputShifter/MFInputShifter.h
Buttons and input shifters are initialized with the actual status of inputs.
This avoids serial messages an startup due to changed status of inputs in case they are closed (ON).
Fixes #200
=> Improve getting correct device infos for connector from Mega

README.md
Fixes #195
Remove the open in vscode line since nobody likely ever used it and the image was broken.
=> Remove link to Open in VSCode

src/MF_DigInMux/MFDigInMux.cpp, src/MF_DigInMux/MFDigInMux.h, src/MF_InputShifter/MFInputShifter.cpp, src/MF_InputShifter/MFInputShifter.h
Changes:
relates to #201 
fixes #200
=> Use same retrigger logic for Multiplexer and InputShifter

src/MF_DigInMux/DigInMux.cpp, src/MF_DigInMux/DigInMux.h, src/MF_DigInMux/MFDigInMux.cpp, src/MF_DigInMux/MFDigInMux.h
Fixes #204
- Removed `Lazy` code branch and `mode` argument from `MFDigInMux::poll()`
- Removed setLazyMode() (and related enum) from `MFDigInMux.*`
- Removed `mode` argument from `DigInMux::Add`
=> Removed "Lazy" mode from Multiplexer code (#204)

src/MF_Analog/MFAnalog.cpp
Fixes #200 (reopened) but belongs to the scope of the changes made in PR #199.
=> Fix faulty initialization of analog value at startup

_Boards/Atmel/Board_Nano/MFBoards.h, platformio.ini
Fixes #100 
* Add nano to `platformio.ini`
* Add `MFBoards.h` for the nano device
The board file came from @elral.
=> Add Nano support

src/Config.cpp
Store `MOBIFLIGHT_TYPE` in flash and not in RAM.
Easier function to check if a name is available.
Fixes #216
=> MF type to flash, simplier check for serial avail.

src/MF_Analog/MFAnalog.h
Fixes #211
Changed the way of defining the size of the buffer (no change in value)
Added comment
=> Change constant for averaging buffer size of analog inputs (#211)

src/CommandMessenger.cpp, src/Config.cpp, src/MF_Modules/MFEEPROM.cpp, src/MF_Modules/MFEEPROM.h
`read_char()` is renamed to `read_byte()` as mainly a byte is required.
Within `OnGetInfo()` a char is required to send the config via the command messenger, at this point `read_byte()` is casted.
Additional functions to save/read a complete array or struct. This could be helpfull for future use (e.g. parameters for an analog calibration should be in a struct and this struct should be saved to the EEPROM). These additional functions and the existing functions for reading/saving arrays with fixed lenght are moved to `EEPROM.h` in a template.
`storeName()` and `restoreName()` are cleaned up slightly
Fixes #221
=> add write block w/o length, renaming read_char

src/MF_DigInMux/DigInMux.cpp
On startup the constructor for the digital input multiplexer is called and the status of each input gets initialized to the current status. With one of the next steps this status get be cleared again, so on startup serial messages could be generated due to status changes of the inputs.
Furthermore it is not checked like for the other devices if the digital input multiplexer fits into the device buffer.
Calling the clear() function is deleted.
Check if device fits into the device buffer is added.
Fixes #226
=> faulty init on startup, check for available memory

platformio.ini
Fixes #243 
Add a `custom_` prefix to the `lib_deps_Amtel` environment variable to remove the build warning.
=> Add custom_ prefix to remove build warning

src/Config.cpp
Fixes #245 
Removes the unused `temp` variable. The variable was introduced [here](https://github.com/MobiFlight/MobiFlight-FirmwareSource/commit/e00bc34c23328801ca5866886c33a173ba641eb5).
=> Remove unused temp variable

_Boards/Atmel/Board_Nano/MFBoards.h, _Boards/Atmel/Board_ProMicro/MFBoards.h
This PR will increase the Analog Input on the Nano to 8 and on the ProMicro to 9
For the Nano with the limited device buffer additional devices could be limited, depending on the memory consumption for other devices.
Implementing PR #219  will increase the max. number of devices which can be configured.
Fixes #247
=> Increase Analog Input on Nano/ProMicro

_Boards/Atmel/Board_Mega/MFBoards.h, _Boards/Atmel/Board_Nano/MFBoards.h, _Boards/Atmel/Board_ProMicro/MFBoards.h, _Boards/Atmel/Board_Uno/MFBoards.h, _Boards/RaspberryPi/Pico/MFBoards.h
Fixes #249 
Add `#ifndef` around all of the defines in the MFBoard.h files. Doesn't result in any change in functionality, just enables setting them via environment variables in the future.
=> Wrap defines

src/MF_DigInMux/DigInMux.cpp, src/allocateMem.cpp
Define `DEBUG2MSG` replaced by `DEBUG2CMDMESSENGER `to get this info during debuging to the connector.
Added an additionally print to the connector to get the size of devices which gets registered in the device buffer.
Fixes #254
=> Wrong define for debug message to connector

src/MF_DigInMux/DigInMux.cpp
In the `for` loop the array `digInMux[]` gets not exceeded anymore as `i` is used instead of`digInMuxRegistered` for the array index.
Fixes #255
=> Fixed exceeding digInMux array

_Boards/Atmel/Board_Nano/MFBoards.h, _Boards/Atmel/Board_ProMicro/MFBoards.h, _Boards/Atmel/Board_Uno/MFBoards.h, platformio.ini, src/MF_Segment/LedControl_dual.cpp, src/MF_Segment/LedControl_dual.h, src/MF_Segment/MFSegments.h
Replaced stock LedControl library with dual MAX/TM library; increased display number for smaller Arduinos from 1 to 3
Fixes #251
Adding these units as new, independent devices is almost unfeasible because of memory (mainly flash) constraints on the smaller (Arduino) boards.
This implementation extends the standard MAX72xx LedControl driver with a dual low-level layer, keeping perfect compatibility in the upper interface layer; this way, it doesn't call for the overhead of an additional device type, and also it doesn't require changes in the message set.
=> Added support for TM1637 displays

src/Config.cpp, src/MF_Segment/LedControl_dual.cpp, src/MF_Segment/LedControl_dual.h, src/MF_Segment/LedSegment.cpp, src/MF_Segment/LedSegment.h, src/MF_Segment/MFSegments.cpp, src/MF_Segment/MFSegments.h, src/config.h
Fixes #251 
_Describe changes here_
- Introduced type instead of using the CS pin
- Memory improvements.
```
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [========  ]  77.3% (used 1978 bytes from 2560 bytes)
Flash: [==========]  99.9% (used 28630 bytes from 28672 bytes)
```
```
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [========  ]  77.3% (used 1978 bytes from 2560 bytes)
Flash: [==========]  99.1% (used 28422 bytes from 28672 bytes)
```
=> TM1637 memory and code structure improvements

src/Config.cpp
We introduced a new macro #define `MEMLEN_NAMES_BUFFER` to reduce the size / length of the `nameBuffer`.
By accident, the init code still uses the old name `MEM_LEN_CONFIG` which is using a bigger value. 
This PR uses the correct macro: `MEMLEN_NAMES_BUFFER` for intializiing `nameBuffer`
=> Use correct size for nameBuffer

_Boards/Atmel/Board_Mega/MFBoards.h, _Boards/Atmel/Board_Nano/MFBoards.h, _Boards/Atmel/Board_ProMicro/MFBoards.h, _Boards/Atmel/Board_Uno/MFBoards.h, _Boards/RaspberryPi/Pico/MFBoards.h, platformio.ini, src/MF_Modules/MFEEPROM.cpp
Custom Devices are not a basic device, so `MF_CUSTOMDEVICE_SUPPORT` should be set to 0 or should be just not defined. So `#define MF_CUSTOMDEVICE_SUPPORT 1` / `#define MF_CUSTOMDEVICE_SUPPORT 2`  is deleted in all board.h files and in the platformio.ini file.
In the xyz_custom.ini files this definition is already included to get the custom devices compiled.
/edit: Fixes #263
=> Fix board files

.github/release.yml
=> Improve auto-generated release notes

src/allocateMem.cpp, src/allocateMem.h
With PR #253 the limitation for the max devices per type was eliminated.
Before this PR memory was allocated in the device buffer for each single device. The highest amount of memory is 31 byte for one encoder.
Now the memory gets allocated in the device buffer for all devices of one type at once. If the required memory is more than 255 bytes, e.g. 9 encoders need 9 * 31bytes = 279 bytes, only 23 bytes gets reserved as the size to allocate memory is limited to a byte.
In `allocateMem.cpp/.h` the variable `size` within the functions `allocateMemory()` and `FitInMemory()` must be defined as `uint16_t`.
Fixes #271
=> Beta - Fix memory overlap in DeviceBuffer

src/Config.cpp, src/MF_Stepper/MFStepper.cpp, src/MF_Stepper/MFStepper.h
With the code changes done with PR #261 the structure for reading the stepper config was bundled and slightly changed.
While the config gets read from the eeprom, the parameter are assigned to an array and this array is used for the parameters of the `Stepper::Add(params[0], params[1], params[2], params[3], params[4], params[5], params[6], params[7]);` function.
For the actual stepper type the button gets not read which is now added with this PR. Furthermore sending commands to an not initialized stepper will be blocked
If the button gets not read, the next read command, which is reading the stepper mode, reads the button number. So the button number is treated as stepper mode. Within the stepper code it's checked if it's a valid mode. If not, and that's for all button numbers bigger then …
=> Beta - Board wont crash if limit switch for steppers is configured

src/CommandMessenger.cpp, src/Config.cpp, src/MF_Button/MFButton.cpp, src/MF_CustomDevice/CustomDevice.cpp, src/MF_Encoder/MFEncoder.cpp, src/MF_InputShifter/InputShifter.cpp, src/MF_LCDDisplay/LCDDisplay.cpp, src/MF_Output/Output.cpp, src/MF_OutputShifter/OutputShifter.cpp, src/MF_Segment/LedSegment.cpp, src/MF_Servo/Servos.cpp, src/MF_Stepper/Stepper.cpp, src/mobiflight.cpp
Fixes #273
This PR fundamentally changes how the firmware knows when to keep displays awake.
Instead of relying on the firmware to track when various events happen (and missing some events, like buttons, encoders, and multiplexers), it simply relies on the desktop app to tell it to stay awake.
The companion desktop app change sends a keep alive message every 5 minutes. If it's been 15 minutes since one of those messages came in the firmware will put displays to sleep.
Bonus: Removing all the calls to `setLastCommandMillis` saves about 1k of space (at least for the pico)
=> Support keep alive messages from the desktop app

.github/workflows/ci.yml, .github/workflows/release.yml
Fixes #235
* Explicitly set the python version to use
* Add proper caching for PlatformIO
Build time without cache: 7 minutes 13 seconds
Build time with cache: 3 minutes 34 seconds
=> Clean up the build scripts

platformio.ini
With PR #258 custom devices were added. Accidently `'-DMOBIFLIGHT_TYPE="MobiFlight Micro"'` was added to the `platformio.ini` file, but as it is a standard definition it belongs to MFBoards.h``where it is still part of this file. So no need to do it in `platformio.ini`.
For custom devices this definition is still required to have it in the custom ini file to override the standard type.
=> MOBIFLIGHT_TYPE is already defined in MFBoards.h

src/MF_Output/MFOutput.cpp, src/MF_Output/MFOutput.h, src/MF_Output/Output.cpp
On the Pico two pins get set at the same time if both pins are configured as output and the difference of the pin numbers are 16.
Moving the initialization of the pin from the class `MFOutput()` to the function which calls the initialization `Output::Add()` solves this issue.
For now it is unclear why this change fixes it. More investigation has to be done.
The change is only done for the Pico and not for the other boards.
Additionally changes are implemented to fix issue #284 to avoid merge errors when both PR gets merged. An additional comment will be given in the upcoming PR.
Fixes #283
=> Two pins get set on Pico Board

src/MF_Analog/Analog.cpp, src/MF_Analog/MFAnalog.cpp, src/MF_Analog/MFAnalog.h, src/MF_Button/Button.cpp, src/MF_Button/MFButton.cpp, src/MF_Button/MFButton.h, src/MF_CustomDevice/CustomDevice.cpp, src/MF_InputShifter/MFInputShifter.cpp, src/MF_InputShifter/MFInputShifter.h, src/MF_Segment/LedSegment.cpp, src/MF_Servo/MFServo.cpp, src/MF_Servo/MFServo.h, src/MF_Stepper/MFStepper.h
For the devices `AnalogIn` and `Buttons` an `attach()` function ia added where all required init paramaters are transferred. These init parameters were part of the constructor.
Now calling the constructor will only set that the device is not initialized.
The calling of the constructor is since PR #253 also done to calculate the required memory for all devices of one type and to reserve it.  As no init parameters are available at this point the standard paramaters were taken and e.g. pin 1 for the output and analogIn device was set output / input.
The required changes for outputs are part of PR #285.
For the InputShifter the default value in the constructor is deleted. Not required here as it gets set also in the attach() function.
For the servo device the not required constructor was …
=> init devices with attach() function and not via constructor

src/MF_Output/MFOutput.cpp, src/MF_Output/Output.cpp
Further evaluation of issue #283 showed that PR #285 didn't solve the issue.
Pico is limited to one bank of 16 PWM timer starting at Pin 0. If using a pin > 15 also as PWM output, these pins get doubled.
E.g. using pin 2 as PWM output and unsing pin 18 as PWM output each change on pin 2 or pin 18 will also set the other one.
If one of these pins are used as a digital output everything is fine.
Within the code for the outputs `analogWrite()` is always used toset an output. Doing it this way each pin is used as PWM output for the Pico and the above problem occurs. The only way to solve it is to use only the first 16 pins as PWM output. This change will be done in a separate PR to adapt the `raspberrypi_pico.board.json` by setting `"isPWM": false` for pins > 15. So for pins > 15 the value …
=> Double set pin

.github/release.yml
We are using beta-bugs as label in this repository but it was not part of the release.yml
fixes #269
=> Added beta-bug label for release notes
